-- Daily AI coaching tip cache per employee.
-- Generated by Claude Haiku once per day and cached here so the UI is instant.
-- One tip per (slug, brand, calendar date).

CREATE TABLE IF NOT EXISTS employee_daily_tip (
  id           SERIAL PRIMARY KEY,
  slug         TEXT NOT NULL,
  brand        TEXT NOT NULL DEFAULT 'spa',
  tip_text     TEXT NOT NULL,
  generated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  period_from  DATE,
  period_to    DATE,
  UNIQUE (slug, brand, (generated_at::date))
);

CREATE INDEX IF NOT EXISTS employee_daily_tip_lookup_idx
  ON employee_daily_tip (slug, brand, generated_at DESC);
